default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  password: Priscilla4God
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogapp_development
 
test:
  <<: *default
  database: blogapp_test

production:
  <<: *default
  database: blogapp_production
  username: blogapp
  password: <%= ENV["BLOGAPP_DATABASE_PASSWORD"] %>
